In [25]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [26]:
df = pd.DataFrame([[9,8,5],[8,8,4],[7,6,3],[6,5,2],[5,4,1],[4,3,1]], columns=['Feature1', 'Feature2', 'Target'])

In [27]:
df

,Feature1,Feature2,Target
0,9,8,5
1,8,8,4
2,7,6,3
3,6,5,2
4,5,4,1
5,4,3,1


In [40]:
def initialize_parameters(layer_dims):
    np.random.seed(12)
    parameters = {}
    for l in range(1, len(layer_dims)):
        parameters['W' + str(l)] = np.random.randn(layer_dims[l], layer_dims[l-1]) * 0.1 #matrix of current layer and previous layer for weights
        parameters['b' + str(l)] = np.zeros((layer_dims[l], 1)) #matrix of current bias layer and 1 column

    return parameters

In [46]:
parameters = initialize_parameters([2, 2, 1])
parameters

{'W1': array([[ 0.04729858, -0.06814259],
        [ 0.02424395, -0.17007356]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[ 0.07531428, -0.15347213]]),
 'b2': array([[0.]])}

In [51]:
def linear_forward(A_prev, W, b):
    z = np.dot(W, A_prev) + b
    return z

In [121]:
def L_layer_forward(x,parameters):
    a = x
    l = len(parameters) // 2

    for i in range(1, l+1):
        a_prev = a
        wl = parameters['W' + str(i)]
        bl = parameters['b' + str(i)]
        # print("A"+str(i-1)+ ": ", a_prev)
        # print("W"+str(i)+ ": ", wl)
        # print("b"+str(i)+ ": ", bl)
        # print("--"*15)

        a = linear_forward(a_prev, wl, bl)
        # print("a"+str(i)+ ": ", a)
        # print("=="*15)

    return a, a_prev


In [122]:
x = df[['Feature1', 'Feature2']].values[0].reshape(2,1) # Convert to column vector
y = df['Target'].values[0].reshape(1,1) # Convert to column vector


In [123]:
y

array([[5]])

In [124]:
parmeters = initialize_parameters([2, 2, 1])
y_hat, A1 = L_layer_forward(x, parmeters)

In [125]:
(y-0.166) ** 2

array([[23.367556]])

In [126]:
y_hat = y_hat[0][0]

In [127]:
a1

array([[-0.11945346],
       [-1.14239296]])

In [128]:
def update_paramters(parameters, y , y_hat, a1, x):
    error = (y - y_hat).item()
    parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (error) * a1[0][0])
    parameters['W2'][0][1] = parameters['W2'][0][1] + (0.001 * 2 * (error) * a1[1][0])
    parameters['b2'][0][0] = parameters['b2'][0][0] + (0.001 * 2 * (error) * 1)

    parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (error) * parameters['W2'][0][0] * x[0][0])
    parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (error) * parameters['W2'][0][0] * x[1][0])
    parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (error) * parameters['W2'][0][0] * 1)

    parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (error) * parameters['W2'][0][1] * x[0][0])
    parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (error) * parameters['W2'][0][1] * x[1][0])
    parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (error) * parameters['W2'][0][1] * 1)
    return parameters
    

In [129]:
update_paramters(parameters, y , y_hat, A1, x)

{'W1': array([[ 0.15932733,  0.03462019],
        [-0.33859649, -0.50358184]]),
 'b1': array([[ 0.01301812],
        [-0.04145849]]),
 'W2': array([[ 0.13998141, -0.53743733]]),
 'b2': array([[0.1381032]])}

In [136]:
#epoch implementation
parameters = initialize_parameters([2, 2, 1])
epochs = 10

for i in range(epochs):
    loss = [0]

    for j in range(df.shape[0]):
        x = df[['Feature1', 'Feature2']].values[j].reshape(2,1) # Convert to column vector
        y = df['Target'].values[j].reshape(1,1) # Convert to column vector

        y_hat, A1 = L_layer_forward(x, parameters)
        y_hat = y_hat[0][0]
        loss.append(((y - y_hat) ** 2).item())
        parameters = update_paramters(parameters, y , y_hat, A1, x)
    print('Epoch: ', i+1, ' Loss: ', np.array(loss).mean())
print(parameters)

Epoch:  1  Loss:  7.111333725049713
Epoch:  2  Loss:  6.2659086448048
Epoch:  3  Loss:  5.149803785579299
Epoch:  4  Loss:  3.827468725023743
Epoch:  5  Loss:  2.5397177031123475
Epoch:  6  Loss:  1.563960303682084
Epoch:  7  Loss:  0.9925018452188837
Epoch:  8  Loss:  0.7211179685130514
Epoch:  9  Loss:  0.6070292884962852
Epoch:  10  Loss:  0.5602492978836789
{'W1': array([[ 0.14714809,  0.0237942 ],
       [-0.29183617, -0.46201712]]), 'b1': array([[ 0.01166488],
       [-0.0362629 ]]), 'W2': array([[ 0.1411362 , -0.52639343]]), 'b2': array([[0.12843585]])}
